 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/viewing_forms", type: :request do
  
  # ViewingForm. As you add validations to ViewingForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ViewingForm.create! valid_attributes
      get viewing_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      viewing_form = ViewingForm.create! valid_attributes
      get viewing_form_url(viewing_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_viewing_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      viewing_form = ViewingForm.create! valid_attributes
      get edit_viewing_form_url(viewing_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ViewingForm" do
        expect {
          post viewing_forms_url, params: { viewing_form: valid_attributes }
        }.to change(ViewingForm, :count).by(1)
      end

      it "redirects to the created viewing_form" do
        post viewing_forms_url, params: { viewing_form: valid_attributes }
        expect(response).to redirect_to(viewing_form_url(ViewingForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ViewingForm" do
        expect {
          post viewing_forms_url, params: { viewing_form: invalid_attributes }
        }.to change(ViewingForm, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post viewing_forms_url, params: { viewing_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested viewing_form" do
        viewing_form = ViewingForm.create! valid_attributes
        patch viewing_form_url(viewing_form), params: { viewing_form: new_attributes }
        viewing_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the viewing_form" do
        viewing_form = ViewingForm.create! valid_attributes
        patch viewing_form_url(viewing_form), params: { viewing_form: new_attributes }
        viewing_form.reload
        expect(response).to redirect_to(viewing_form_url(viewing_form))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        viewing_form = ViewingForm.create! valid_attributes
        patch viewing_form_url(viewing_form), params: { viewing_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested viewing_form" do
      viewing_form = ViewingForm.create! valid_attributes
      expect {
        delete viewing_form_url(viewing_form)
      }.to change(ViewingForm, :count).by(-1)
    end

    it "redirects to the viewing_forms list" do
      viewing_form = ViewingForm.create! valid_attributes
      delete viewing_form_url(viewing_form)
      expect(response).to redirect_to(viewing_forms_url)
    end
  end
end
